# SPDX-FileCopyrightText: 2026 Fengrímur
# SPDX-License-Identifier: AGPL-3.0-only
# See NOTICE for additional terms.

from __future__ import annotations

import argparse
import logging
import sys

from .config import load_config
from .ledger import Ledger
from .model import ConfigError, InvariantViolation, LedgerUnavailable, OperatorRefused, utc_now
from .runner import run_tick

EXIT_OK = 0
EXIT_MUTEX_BUSY = 1
EXIT_LEDGER_UNAVAILABLE = 2
EXIT_CONFIG = 3
EXIT_OPERATOR_REFUSED = 4
EXIT_INVARIANT = 5

RESOLVE_OUTCOMES = ("failed", "closed-unverified")


def render_toolforge_job(cfg) -> str:
    return (
        "# Generated by `purgebot render-job`; the values come from [safety].\n"
        "---\n"
        "- name: purgebot\n"
        "  image: python3.13\n"
        "  command: ./venv/bin/purgebot run --config ./config.toml\n"
        f"  schedule: \"{cfg.safety.tick_cron}\"\n"
        f"  timeout: {cfg.safety.platform_timeout_s}\n"
        "  retry: 0\n"
        "  emails: onfailure\n"
    )


def with_ledger(cfg, operation) -> int:
    db = Ledger.connect(cfg.database)
    try:
        if not db.acquire_mutex():
            print("another worker holds the ledger mutex", file=sys.stderr)
            return EXIT_MUTEX_BUSY
        db.require_schema(1)
        operation(db)
        return EXIT_OK
    finally:
        db.close_releasing_mutex_if_healthy()


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="purgebot")
    parser.add_argument("--log-level", default="INFO",
                        choices=("DEBUG", "INFO", "WARNING", "ERROR"))
    commands = parser.add_subparsers(dest="command", required=True)

    for name in ("run", "render-job"):
        sub = commands.add_parser(name)
        sub.add_argument("--config", required=True)

    operator = commands.add_parser("operator")
    operations = operator.add_subparsers(dest="operation", required=True)

    resume = operations.add_parser("resume-job")
    resume.add_argument("job_id", type=int)

    resolve = operations.add_parser("resolve-target")
    resolve.add_argument("target_id", type=int)
    resolve.add_argument("--outcome", required=True, choices=RESOLVE_OUTCOMES)

    cancel = operations.add_parser("cancel-job")
    cancel.add_argument("job_id", type=int)

    for sub in (resume, resolve, cancel):
        sub.add_argument("--config", required=True)
        sub.add_argument("--operator", required=True)
        sub.add_argument("--reason", required=True)
    return parser


def run_operator_command(cfg, args) -> int:
    now = utc_now()
    if args.operation == "resume-job":
        return with_ledger(cfg, lambda db: db.operator_resume_job(
            args.job_id, args.operator, args.reason, cfg.safety, now))
    if args.operation == "resolve-target":
        return with_ledger(cfg, lambda db: db.operator_resolve_target(
            args.target_id, args.outcome, args.operator, args.reason, now))
    return with_ledger(cfg, lambda db: db.operator_cancel_job(
        args.job_id, args.operator, args.reason, now))


def main(argv=None) -> int:
    args = build_parser().parse_args(argv)
    logging.basicConfig(level=args.log_level,
                        format="%(asctime)s %(levelname)s %(name)s %(message)s")
    try:
        cfg = load_config(args.config)
        if args.command == "render-job":
            print(render_toolforge_job(cfg), end="")
            return EXIT_OK
        if args.command == "run":
            return run_tick(cfg)
        return run_operator_command(cfg, args)
    except ConfigError as exc:
        print(f"configuration rejected: {exc}", file=sys.stderr)
        return EXIT_CONFIG
    except OperatorRefused as exc:
        print(f"operator command refused: {exc}", file=sys.stderr)
        return EXIT_OPERATOR_REFUSED
    except LedgerUnavailable as exc:
        print(f"ledger unavailable: {exc}", file=sys.stderr)
        return EXIT_LEDGER_UNAVAILABLE
    except InvariantViolation as exc:
        print(f"invariant violation: {exc}", file=sys.stderr)
        return EXIT_INVARIANT


if __name__ == "__main__":
    sys.exit(main())
